// Coffee Types
export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PROFILE = "FETCH_PROFILE";
// Cart Types
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const POST_CHECKOUT = "POST_CHECKOUT";
export const SET_CURRENT_USER = "SET_CURRENT_USER;";
export const SET_ERROR = "SET_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ADDRESSES = "FETCH_ADDRESSES";
export const CREATE_ADDRESS = "FETCH_ADDRESS";
export const SET_ADDRESS = "SET_ADDRESS";

// export const SET_CURRENT_USER = "SET_CURRENT_USER";
// export const SET_ERRORS = "SET_ERRORS";

// export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
// export const FETCH_PRODUCT = "FETCH_PRODUCT";
// export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";
// export const SET_ADDRESS_LOADING = "SET_PRODUCT_LOADING";
// export const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING";
// export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
// export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
// export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING";
// export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
// export const ADD_PRODUCT = "ADD_PRODUCT";
// export const POST_CHECKOUT = "POST_CHECKOUT";
// export const REMOVE_ITEM = "REMOVE_ITEM";
// export const FETCH_ADDRESSES = "FETCH_ADDRESSES";
// export const CREATE_ADDRESS = "FETCH_ADDRESS";
// export const SET_ADDRESS = "SET_ADDRESS";
// export const FETCH_ORDERS = "FETCH_ORDERS";
// export const FETCH_ORDER = "FETCH_ORDER";
// export const SET_ORDER_LOADING = "SET_ORDER_LOADING";
// export const SET_ORDERS_LOADING = "SET_ORDERS_LOADING";
